# Generated by Django 5.2.3 on 2025-07-01 08:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Hw2", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
