# Generated by Django 5.2.3 on 2025-07-01 09:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Hw2", "0002_order"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Activity",
        ),
        migrations.DeleteModel(
            name="Order",
        ),
    ]
